FROM node:18-alpine
WORKDIR /app

# Install deps
COPY frontend/package*.json ./
RUN npm ci

# Build
COPY frontend/ ./
RUN npm run build && npm i -g serve

EXPOSE 3000
CMD ["serve", "-s", "build", "-l", "3000"]


