#!/bin/bash

# CreatorSync - Real API Setup Script
# This script will guide you through setting up real social media APIs

echo "🚀 CreatorSync - Real API Setup Script"
echo "======================================"
echo ""

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Function to print colored output
print_info() {
    echo -e "${BLUE}ℹ️  $1${NC}"
}

print_success() {
    echo -e "${GREEN}✅ $1${NC}"
}

print_warning() {
    echo -e "${YELLOW}⚠️  $1${NC}"
}

print_error() {
    echo -e "${RED}❌ $1${NC}"
}

# Function to create environment file
create_env_file() {
    local platform=$1
    local env_file="back/backend-node/.env"
    
    echo "" >> "$env_file"
    echo "# $platform API Configuration" >> "$env_file"
    echo "# Generated by setup-real-apis.sh" >> "$env_file"
    echo "${platform^^}_API_URL=$2" >> "$env_file"
    echo "${platform^^}_ACCESS_TOKEN=$3" >> "$env_file"
    echo "${platform^^}_APP_ID=$4" >> "$env_file"
    echo "" >> "$env_file"
    
    print_success "Added $platform configuration to $env_file"
}

# Function to validate URL
validate_url() {
    local url=$1
    if [[ $url =~ ^https?:// ]]; then
        return 0
    else
        return 1
    fi
}

# Function to validate token format
validate_token() {
    local token=$1
    if [[ ${#token} -gt 50 ]]; then
        return 0
    else
        return 1
    fi
}

# Function to validate app ID
validate_app_id() {
    local app_id=$1
    if [[ $app_id =~ ^[0-9]+$ ]]; then
        return 0
    else
        return 1
    fi
}

# Main setup function
setup_platform() {
    local platform=$1
    local platform_name=$2
    local api_url=$3
    
    echo ""
    print_info "Setting up $platform_name API..."
    echo "======================================"
    
    # Get API URL
    echo -n "Enter $platform_name API URL (press Enter for default: $api_url): "
    read user_api_url
    if [[ -z "$user_api_url" ]]; then
        user_api_url=$api_url
    fi
    
    if ! validate_url "$user_api_url"; then
        print_error "Invalid URL format. Please enter a valid URL starting with http:// or https://"
        return 1
    fi
    
    # Get App ID
    echo -n "Enter your $platform_name App ID: "
    read app_id
    if ! validate_app_id "$app_id"; then
        print_error "Invalid App ID. Please enter a numeric App ID."
        return 1
    fi
    
    # Get Access Token
    echo -n "Enter your $platform_name Access Token: "
    read -s access_token
    echo ""
    if ! validate_token "$access_token"; then
        print_error "Invalid Access Token. Please enter a valid token (should be longer than 50 characters)."
        return 1
    fi
    
    # Confirm details
    echo ""
    print_info "Please confirm your $platform_name details:"
    echo "API URL: $user_api_url"
    echo "App ID: $app_id"
    echo "Access Token: ${access_token:0:20}..."
    
    echo -n "Is this correct? (y/n): "
    read confirm
    if [[ $confirm != "y" && $confirm != "Y" ]]; then
        print_warning "Setup cancelled for $platform_name"
        return 1
    fi
    
    # Create environment file
    create_env_file "$platform" "$user_api_url" "$access_token" "$app_id"
    
    # Test the API connection
    echo ""
    print_info "Testing $platform_name API connection..."
    test_api_connection "$platform" "$user_api_url" "$access_token"
    
    return 0
}

# Function to test API connection
test_api_connection() {
    local platform=$1
    local api_url=$2
    local access_token=$3
    
    # Test endpoint based on platform
    local test_endpoint=""
    case $platform in
        "instagram"|"facebook")
            test_endpoint="$api_url/me?access_token=$access_token"
            ;;
        "tiktok")
            test_endpoint="$api_url/user/info?access_token=$access_token"
            ;;
        "linkedin")
            test_endpoint="$api_url/me?oauth2_access_token=$access_token"
            ;;
        "twitter")
            test_endpoint="$api_url/users/me"
            ;;
        *)
            test_endpoint="$api_url/me?access_token=$access_token"
            ;;
    esac
    
    echo "Testing: $test_endpoint"
    
    # Make API call (with timeout)
    response=$(curl -s -m 10 "$test_endpoint" 2>/dev/null)
    
    if [[ $? -eq 0 && -n "$response" ]]; then
        print_success "$platform_name API connection successful!"
        echo "Response preview: ${response:0:100}..."
    else
        print_warning "$platform_name API connection failed or timed out."
        print_info "This might be normal if the token needs additional setup."
    fi
}

# Function to show setup instructions
show_setup_instructions() {
    local platform=$1
    local platform_name=$2
    
    echo ""
    print_info "📋 $platform_name Setup Instructions:"
    echo "======================================"
    
    case $platform in
        "instagram")
            echo "1. Go to https://developers.facebook.com/"
            echo "2. Create a new 'Business' app"
            echo "3. Add 'Instagram Basic Display' product"
            echo "4. Go to Settings → Basic to get App ID"
            echo "5. Go to Tools → Graph API Explorer"
            echo "6. Add permissions: instagram_basic, instagram_content_publish"
            echo "7. Generate Access Token"
            echo ""
            print_warning "Note: Your Instagram account must be a Business/Creator account"
            ;;
        "facebook")
            echo "1. Go to https://developers.facebook.com/"
            echo "2. Create a new 'Business' app"
            echo "3. Add 'Facebook Login' product"
            echo "4. Go to Settings → Basic to get App ID"
            echo "5. Go to Tools → Graph API Explorer"
            echo "6. Add permissions: pages_manage_posts, pages_read_engagement"
            echo "7. Generate Access Token"
            ;;
        "tiktok")
            echo "1. Go to https://developers.tiktok.com/"
            echo "2. Create a new app"
            echo "3. Enable Content Publishing"
            echo "4. Get App ID and Access Token from dashboard"
            ;;
        "linkedin")
            echo "1. Go to https://www.linkedin.com/developers/"
            echo "2. Create a new app"
            echo "3. Request access to Marketing APIs"
            echo "4. Get App ID and Access Token"
            ;;
        "twitter")
            echo "1. Go to https://developer.twitter.com/"
            echo "2. Create a new app"
            echo "3. Enable OAuth 2.0"
            echo "4. Get API Key and Access Token"
            ;;
        "youtube")
            echo "1. Go to https://console.developers.google.com/"
            echo "2. Create a new project"
            echo "3. Enable YouTube Data API v3"
            echo "4. Create credentials (API Key)"
            ;;
    esac
    
    echo ""
    echo "Press Enter when you have your API credentials ready..."
    read
}

# Main script execution
main() {
    echo "This script will help you set up real social media APIs for CreatorSync."
    echo ""
    print_warning "Before starting, make sure you have:"
    echo "- A Facebook Developer account (for Instagram/Facebook)"
    echo "- A TikTok Developer account (for TikTok)"
    echo "- A LinkedIn Developer account (for LinkedIn)"
    echo "- A Twitter Developer account (for Twitter)"
    echo "- A Google Cloud account (for YouTube)"
    echo ""
    
    echo -n "Do you want to continue? (y/n): "
    read continue_setup
    if [[ $continue_setup != "y" && $continue_setup != "Y" ]]; then
        print_info "Setup cancelled. You can run this script again later."
        exit 0
    fi
    
    # Check if .env file exists
    if [[ ! -f "back/backend-node/.env" ]]; then
        print_error "Environment file not found. Please make sure you're running this script from the CreatorSync root directory."
        exit 1
    fi
    
    # Create backup of existing .env file
    cp "back/backend-node/.env" "back/backend-node/.env.backup.$(date +%Y%m%d_%H%M%S)"
    print_success "Created backup of existing .env file"
    
    # Setup each platform
    platforms=(
        "instagram:Instagram:https://graph.facebook.com/v18.0"
        "facebook:Facebook:https://graph.facebook.com/v18.0"
        "tiktok:TikTok:https://open.tiktokapis.com/v2"
        "linkedin:LinkedIn:https://api.linkedin.com/v2"
        "twitter:Twitter:https://api.twitter.com/2"
        "youtube:YouTube:https://www.googleapis.com/youtube/v3"
    )
    
    for platform_info in "${platforms[@]}"; do
        IFS=':' read -r platform platform_name api_url <<< "$platform_info"
        
        echo ""
        echo -n "Do you want to set up $platform_name API? (y/n): "
        read setup_platform
        if [[ $setup_platform == "y" || $setup_platform == "Y" ]]; then
            show_setup_instructions "$platform" "$platform_name"
            setup_platform "$platform" "$platform_name" "$api_url"
        else
            print_info "Skipping $platform_name setup"
        fi
    done
    
    # Final summary
    echo ""
    echo "🎉 API Setup Complete!"
    echo "====================="
    print_success "Your environment file has been updated with the API configurations."
    echo ""
    print_info "Next steps:"
    echo "1. Restart your CreatorSync app: ./start-app.sh"
    echo "2. Test the APIs through the scheduler"
    echo "3. Check the logs for any connection issues"
    echo ""
    print_warning "Remember:"
    echo "- Access tokens expire and need to be refreshed"
    echo "- Keep your .env file secure and never commit it to version control"
    echo "- Test your APIs in development before going to production"
    echo ""
    print_success "Happy posting! 🚀"
}

# Run the main function
main "$@"
