FROM node:18-alpine
WORKDIR /app

# Install deps
COPY frontend/package*.json ./
# Use npm install to avoid lockfile requirement in ci
RUN npm install

# Build
COPY frontend/ ./
RUN npm run build && npm i -g serve

EXPOSE 3000
CMD ["serve", "-s", "build", "-l", "3000"]

